### ISSUE TITLE
Correct way of binding to check boxes and radio buttons

### ISSUE THREAD

**Issue by nareshbhatia** [NYTimes/backbone.stickit#103]
I wanted to make sure that I was binding to check boxes and radio buttons correctly. Please see this jsFiddle: http://jsfiddle.net/nareshbhatia/jjdm5/

Specifically:
- The HTML markup for a group of check boxes should have the same class. Same is true for a group of radio buttons.
- A group of radio buttons should, in addition, have the same name attribute. This is not required for check boxes.

**Comment by clintonb** [comment]
@delambo I found this issue after having issues binding to my radio group's name...

This does not work:
```javascript
bindings: {
  'input[name=id_verification_required]': 'id_verification_required'
}
```

However, after reading @nareshbhatia's comment, an update to using a class selector does:
```javascript
bindings: {
  '.idvr': 'id_verification_required'
}

Any idea why the name selector doesn't work, yet the class selector does? This doesn't seem to be documented anywhere. I am happy to open a PR if someone can explain why the name selector fails.

**Comment by clintonb** [comment]
Disregard the above comment. I just realized I had a hidden field with the name attribute set to id_verification_required.
