### ISSUE TITLE
Cursor jumps to end of input when using Stickit + Html5 email input type and webkit

### ISSUE THREAD

**Issue by kbaribeau** [NYTimes/backbone.stickit#15]
Hey all,

I just started using stickit and I love it, BUT, I have this issue.

If my template is using the html5 email input type like so:

``` html
<input type="email" name="email" class="span12" required />
```

In my view I have these bindings:

``` coffeescript
  bindings:
    "input[name=email]":
      modelAttr: "email"
```

Typing initially into the textbox is fine, but when I try to change it, my cursor gets moved to the end of the line.

Here's a short video: https://dl.dropbox.com/u/80354/stickit-thing.swf

I was able to reproduce this in Safari, Chrome, and the iOS Simulator, but not Firefox.

Thanks!

**Comment by mrchimp** [comment]
Just leaving this here in case it helps somebody... I was having the same issue. It turned out I was calling this.stickit() on my view every time the model was validated, which was on each keypress... If you call it that much, you're gonna have a bad time.
