### ISSUE TITLE
doesn't save values from autocomplete fields

### ISSUE THREAD

**Issue by danielmyasnikov** [NYTimes/backbone.stickit#166]
I have plugged autocomplete after in initialize function as advised from stickit documentation.

Almost hello world world example:

<pre>
MyApp.Views.Form = Backbone.View.extend({
    el: "#my-form",
    bindings: {
        "#postcode_with_suburbs": {
            observe: "postcode",
            initialize: function($el, model, options) {
                $el.autocomplete({
                    source: [ "c++", "java", "php", "coldfusion", "javascript", "asp", "ruby" ] 
                })
            },
            onSet: function(val, options) {
                return $("#postcode_with_suburbs").val(); 
            }
        },
    },
    events: {
        "click #form-submit" : "submit",
    },
    initialize : function() {
            this.listenTo(this.model, "change");
            this.render();
    },
    render: function() {
        this.$el.html(JST['backbone/templates/car_insurance/form']);
            this.stickit();
        return this;
    }
});
</pre>

So the problem is whenever a user fills the form and autocomletes the postcode by **clicking** the autocomplete value it is not saved to the model attribute. `Saved as ja` instead of `java`

However scrolling down with a keyboard over the options from an autocomplete, the values is set properly to the attribute of a model. `Saved as java`

**Comment by toabi** [comment]
@delambo I made a fiddle: <http://jsfiddle.net/7wr2vqkz/1/>

Tested the issue in Safari. Chrome doesn't like the fiddle because of external resources. Firefox doesn't offer me any "prefilled" autocompletions which seem to cause the issue.

**Comment by akre54** [comment]
You can't link directly to github, unfortunately. Try rawgit or cdnjs for these resources.

**Comment by toabi** [comment]
Ah, thanks. I updated the fiddle, now it works in Chrome. I can't reproduce it though because I don't have any autocomplete data in Chrome.

http://jsfiddle.net/7wr2vqkz/2/

**Comment by akre54** [comment]
I do have autocomplete data. What should I be looking for? Looks like it's working correctly for me:

![screenshot 2015-05-22 15 19 19](https://cloud.githubusercontent.com/assets/931368/7778092/47e0b4f0-0096-11e5-8d86-5e667438232e.png)

**Comment by toabi** [comment]
Ah, okay, so Chrome works like Firefox where you have to actively select an autocomplete entry. That works.
In Safari, the autocomplete works differently: It fills the field automatically with a proposal. This "filling" doesn't seem to trigger events which would update the model. I don't know how to debug this further properly.

![step-1](https://cloud.githubusercontent.com/assets/115045/7778176/41d9697a-00c9-11e5-9dbc-f04d451c334b.png)

![step-2](https://cloud.githubusercontent.com/assets/115045/7778175/41d2aa5e-00c9-11e5-8ddf-68d774898834.png)

**Comment by akre54** [comment]
That's a good question. What does $(el).val() return on safari?

**Comment by toabi** [comment]
![model.json vs value](https://cloud.githubusercontent.com/assets/115045/7778634/8621ac42-00cd-11e5-8ca6-4c94c4a26514.png)

$(el).val() contains what it should.

Updated fiddle: http://jsfiddle.net/7wr2vqkz/3/

**Comment by akre54** [comment]
Is the problem that it doesn't fire a change event? That might be the place to look.

https://github.com/NYTimes/backbone.stickit/blob/0.9.2/backbone.stickit.js#L436

**Comment by toabi** [comment]
@akre54 I did some research, and this problem is actually quite widespread. Especially with Safari/OSX not firing any events after using autocomplete. (e.g. https://github.com/angular/angular.js/issues/1460, https://github.com/facebook/react/issues/1159 or https://github.com/AmpersandJS/ampersand-input-view/issues/2— I guess the easies fix for me is to turn off autocomplete in the markup.

**Comment by toabi** [comment]
Update: Safari of course also ignores `autocomplete=off` — Is there any easy way to tell stickit to re-read all values from the view/DOM into the model? I could do that the pre-submit at least.

**Comment by toabi** [comment]
Well, by the way, my workaround is to do `$('input').trigger('change')` in some spots of the application. It's a bit ugly, but better than lost data.

**Comment by akre54** [comment]
>  Is there any easy way to tell stickit to re-read all values from the view/DOM into the model?

Not in Stickit, no. You could always serialize the entire form to the model on `submit`, which might solve the issue. This is a really unfortunate bug. 

http://avernet.blogspot.in/2010/11/autocomplete-and-javascript-change.html
