### ISSUE TITLE
afterUpdate not firing 

### ISSUE THREAD

**Issue by rafaelfaria** [NYTimes/backbone.stickit#220]
Hi,

I'm trying to execute a function after the dom has been updated.

I'm trying to use the function afterUpdate but i'm not having much success.

Can someone check my example and let me know what I am doing wrong, or if that's the right way to implement afterUpdate?

http://jsfiddle.net/3xeXk/

Thanks

**Comment by tonglil** [comment]
Is there a way I can force the afterUpdate function to trigger by passing something to change the bind_id or change id? I want to save the model after it gets updated without having the user press a button and would rather not add a listener on each attribute that's being changed.
