### ISSUE TITLE
Does StickIt allow binding to attributes ?

### ISSUE THREAD

**Issue by AaronNGray** [NYTimes/backbone.stickit#273]
Does StickIt allow binding to attributes such as the 'src' URL attribute in a <img> element ?

So I just use jQuery attribute syntax ?
If so the documentation does not mention it or show an example; maybe it should ?

**Comment by delambo** [comment]
Is this what you're looking for:

https://github.com/NYTimes/backbone.stickit#attribute-and-property-bindings

If not, feel free to re-open.
