### ISSUE TITLE
Bower Code does not match master branch.

### ISSUE THREAD

**Issue by rafde** [NYTimes/backbone.stickit#276]
I was testing lodash 3.3.1 against backbone.stickit from bower and found that it broke. There are _.rest functions used in the bower package code that were replaced in the master branch. Please update bower package. Thank you.

Update: Just noticed that the last release is a tag but there hasn't been any activity in this project. Is there going to be an update at any time?
Thanks for reading.

**Comment by akre54** [comment]
Sure, we haven't cut a release in quite a while. Send me a reminder here next week and we'll make sure to do it.

(sent from my phone)

**Comment by rafde** [comment]
You got it. Thanks for the response.

**Comment by akre54** [comment]
Bumped. Give that a try and let me know if it breaks anything for you.

**Comment by rafde** [comment]
It looks like, for my use, it is in the clear. Thank you for the update. I greatly appreciate it.
