### ISSUE TITLE
Nested object support

### ISSUE THREAD

**Issue by pjanuario** [NYTimes/backbone.stickit#281]
I was looking into the documentation and tests and I didn't anything about nested objects.
Is it supported?

```
new Backbone.Model({ address: { street: 'street info', zipCode: 'zipcode'  }});
```

It would be nice if we could register as 
```
bindings: { '#street': 'address.street', '#zipCode': 'address.zipCode' }
```

At the moment I am using set to override this on model, I am not entirely sure even if I should use since I didn't find it on the documentation only through the specs. On this case i just need model update and not view update.

```
bindings: { 
  '#street':  {
     observe: 'address.street',
     set: function(attr, val, options, config) {
         var address = this.model.get('address');
         address.street = val;
          this.model.set('address', address);
         // changing the model address doesn't trigger event change because is same object
         this.model.trigger("change:address");
         this.model.trigger("change");
      }
```

**Comment by yethee** [comment]
Duplicate of #126 
See also #200 and #221

**Comment by pjanuario** [comment]
@yethee on this case I am using stickit with [rendrjs](http://rendrjs.github.io). 

rendr is an isomorphic librabry and their models are an extension to backbone model, so that I am unable to use Backbone Nested or Backbone Deep. :/

Don you know any solution that doesn't include changing my base models? Using mixin maybe or just with stickit code? 

thanks, for the help.

**Comment by yethee** [comment]
You can create a helper model for the struct `address` in the view scope and configure separate bindings for it. This is dirty solution and may break in future versions of Backbone, but should work with Backbone 1.1.2.

```js
Backbone.View.extend({
  bindings: {
    ...
  },
  addressBindings: {
    '#street': 'street',
    '#zipCode': 'zipCode'
  },

  initialize: function(options) {
    this.model = options.model;

    this.address = new Backbone.Model();
    // Use reference on existing object to avoid managing events 
    // for sync between models.
    this.address.attributes = this.model.get('address');

    this.listenTo(this.address, 'change', function(address, options) {
      this.model.trigger('change:address', this.model, address.attributes, options);
    });
  },
  
  render: function() {
    ...

    this.stickit();
    this.stickit(this.address, this.addressBindings);
    
    return this;
  }
});
```

**Comment by pjanuario** [comment]
I was already thinked on this solution, but I was trying to find a better solution without having to a model. Anyway it seems a better solution than the one I have now.
@yethee Thank for your support.
