### ISSUE TITLE
The documentation link in the readme says "0.9.0" but links to documentation for 0.8.0.

### ISSUE THREAD

**Issue by kgodey** [NYTimes/backbone.stickit#282]

**Comment by akre54** [comment]
Sorry about that, our documentation needs to be recompiled on pushes (my fault). Should be good now.

@delambo can we set up a [webhook](http://documentup.com/#hosted/post-receive-hook) to auto-compile doc updates?

**Comment by kgodey** [comment]
@akre54 Thanks! Should I close this issue?

**Comment by akre54** [comment]
Yep. All good.
