### ISSUE TITLE
Support falsy values in classes binding

### ISSUE THREAD

**Issue by bmuenzenmeyer** [NYTimes/backbone.stickit#292]
I love the new [classes hash](http://nytimes.github.io/backbone.stickit/#classes) but find myself at a loss with how to evaluate a falsy value quickly.

Previous to `0.9.*` I had this binding like this:

```javascript
'.disableIcon': {
	attributes: [
		{
			name: 'class',
			observe: 'isDisabled',
			onGet: function(value, options) {
				return value ? 'icon-unlock' : 'icon-lock';
			}
		}
	]
},
```

As far as I understand, I can only replace one side of this situation, like so:

```javascript
'.disableIcon': {
	classes: {
		'icon-unlock': 'isDisabled'
	}
},
```

requiring me to still still evaluate the falsy path using the old attribute syntax.
Would there be some way to accomplish the following?

```javascript
'.disableIcon': {
	classes: {
		'icon-unlock': 'isDisabled',
		'icon-lock': !'isDisabled'
	}
},
```

Not a show stopper, and again, I might be going about it the wrong way. Either way, thanks for the great library!

**Comment by akre54** [comment]
Yeah unfortunately with the simple key -> val syntax it doesn't leave any room for extra options. One idea is we could support `{'icon-unlock': '!isDisabled'}`, and run a regex against the first `!`, but in a perfect world I'd rather we keep away from string programming if we can, as it tends to open a whole slew of new problems. Open to other suggestions if you have any, but I'd say stick with the function for now.

**Comment by bmuenzenmeyer** [comment]
Okay by me - the issue was more a question to make sure I didn't miss something obvious.

Thanks for the quick response!

**Comment by victorwpbastos** [comment]
+1
