### ISSUE TITLE
[Suggestion] "name=" selector

### ISSUE THREAD

**Issue by jeffijoe** [NYTimes/backbone.stickit#293]
I am using Stickit in conjunction with [thedersen/backbone-validation](https://github.com/thedersen/backbone.validation), and so I often do something like this with Stickit:

```javascript
{
  '[name=password]': 'password',
  '[name=password-again]': 'passwordAgain'
}
```

because Backbone.Validation uses the `name` attribute.

I am suggesting a `=[name]` syntax, so the above would become:

```javascript
{
  '=password': 'password',
  '=password-again': 'passwordAgain'
}
```

Thoughts? I would be willing to implement this.

**Comment by aeksco** [comment]
I think this would be an excellent addition - I too am using Backbone.Validation and the ```'[name=attribute]': 'attribute'``` feels repetitive. 

I'm looking into extending the Backbone.Stickit ```view.bindings = {}``` object to leverage the familiar [Backbone.Marionette](https://github.com/marionettejs/backbone.marionette) ```@ui.selector``` syntax to eliminate repeated magic-string selectors:

```coffee
class MyForm extends Marionette.LayoutView

  ui:
    age:    '[name=age]'
    race:   '[name=race]'
    cancel: '[data-click=cancel]'
    submit: '[data-click=submit]'
    region: '[data-region=form]'

  regions:
    formRegion: '@ui.region'

  triggers:
    'click @ui.cancel': 'cancel:event'

  events:
    'click @ui.submit': 'submitCallback'

  bindings:
    '@ui.age':  'age' # this would be so nice
    '@ui.race': 'race'

  onShow: ->
    @ui.race.select2() # https://select2.github.io
```

The ```Marionette.normalizeUIKeys(hash,ui)``` helper method should make this a pretty trivial addition - considering that Marionette already uses it for ```@regions```, ```@triggers```, ```@events```, and [Marionette.Behaviors](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.behaviors.md). 

However given that the ```@ui.selector``` syntax is exclusive to Marionette it's an unlikely candidate for addition to Backbone.Stickit.

In lieu of ```@ui.selector``` syntax I would love short-hand like ```'=attribute': 'attribute'```.

:+1:

**Comment by jeffijoe** [comment]
@aeksco if Stickit added a hook for us to plug this special selector handling in ourselves, that'd solve all our problems.

**Comment by akre54** [comment]
This gets into a bit of "string programming" territory. I think it's much cleaner if it's obvious the keys fall through to real jQuery / qsa selectors. 

What would such a hook look like?

**Comment by vendethiel** [comment]
also seems a bit "it's cute right now, but..."

**Comment by akre54** [comment]
Agreed. You can always pre-process your bindings before passing them to stickit. This isn't something we should be encouraging.
