### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by cancerberoSgx** [NYTimes/backbone.stickit#318]

**Comment by bzalasky** [comment]
The master branch has has several useful commits that haven't been released (lodash@4 compatibility). I'd say Stickit's alive in the sense that plenty of stable projects out there still depend on it. I don't want to speak for anyone else, but I don't anticipate any major changes to Backbone or Stickit at this point.

**Comment by cancerberoSgx** [comment]
@bzalasky Thanks for your thoughts. Last commit to master is more than one year old and it has no forks with commits with less than two years old - so I guess `NYTimes/backbone.stickit/tree/master` has the latest work. 

I understand your point, but our worries are different. Right now we and our users are relying on this library, even as an API, and we are evaluating the effort it could take us maintaining issues in this project by ourselves in case an issue appears.  input binding has a lot to do with validation / model / data and for us issues in this area are critical

We are still in time to choose another library and if we found one that is actively maintained we will evaluate the change - that's why I'm asking. 

I really appreciate authors that admit they are not maintaining the project anymore publicly. I've seen this even in projects that are used a lot in production. If that's the case, a warning message *Looking for maintainers* in the README will only help this project . 

This issue is looking for that information or on the contrarily if this lack of activity is temporary or is because there are no important issues or enhancements planned. My guess is that *this project is not actively maintained because there are commits not released and version is still 0.x* - an active project should aim to reach 1.0 no matter if there is no planned work. Nevertheless I would like to know by main maintainers, so is why I'm tagging them here:  @akre54 @delambo 

Thanks and sorry for the noise but knowing this is very important for us. Thanks!

**Comment by delambo** [comment]
Sorry for the delay. Unfortunately, I haven't had time to come back to this library. I haven't used Backbone or Stickit in several years, so I don't think I'd be a good leader for new development. As suggested, I'll leave a note in the README for a callout to maintainers.

https://github.com/NYTimes/backbone.stickit/issues/319
