### ISSUE TITLE
Binding image or custom binding (and some naming considerations)

### ISSUE THREAD

**Issue by mehcode** [NYTimes/backbone.stickit#41]
If we could have a way to bind images to source URLs that would be good. Right now it just places the URL inside the body of the `<img />` tag (unless I'm missing something).

Also for naming and extensibility I'm thinking of something like this:

``` javascript

bindings: {
  ".photo": {
    observe: "photo",

    // Methods 'get' and 'set' which are in charge of reading / writing the model
    // If set is null then model may not be written to at all
    // This could also be called 'read' and 'write'
    get: function (model, name) { model.get(name); },
    set: function (model, value, name) { model.set(name, value); },

    // Methods 'clean' and 'prepare' which are what onSet and onGet were
    // Instead of updateModel, `clean` could return undefined to signal not to set it
    prepare: function (value, name) { return _(value).prune(15); },
    clean: function (value, name) { return _(value).dasherize(); },

    // Methods 'afterUpdate' and 'update' that correspond to the view; if update is used 
    // it replaces what ever method you're using to update -- afterUpdate is just a hook that 
    // is called after the update method to do whatever (fading, etc)
    // Instead of `updateView`, just set `update` to null
    // `updateMethod` could be kept to allow easy overriding instead of replacing update
    update: function ($el, value, name) { $el.attr('src', value); },

    // Remove visibleFn and have `hide` and `show` callbacks to remove unneeded logic 
    // from consumers code.
    hide: function($el, name) { $el.fadeOut(500); },

    // For.. eventsOverride.. I prefer just 'events' but I can see why you
    // went with eventsOverride.. its just not very succinct -- perhaps another name 
  }
}

```

Just some thoughts to provide flexibility and make it more terse in naming. Not saying that the names must be this. These are just my thoughts on a direction I would go after seeing your awesome library if I were to build it myself.  I just don't like clunky names like `updateModel`, `updateView` (one that takes a function and one that takes a boolean) everywhere. I do want to have the functionality that `update` provides.

---

For some more ideas (that should really have separate issues to discuss them):

As @andriijas mentioned, we do have some nice prototype chain code. I'll submit a PR to add this in if you're interested. This would add the ability for the binding hashes to respect inheritance. 

Another thing is that you could wrap `View#render` to automatically invoke `stickit` if it has not yet been invoked (this would allow for backwards compatibility and more advanced uses like two binding hashes).

**Comment by item-mindi** [comment]
Closing - some of your suggestions were implemented in other issues/PRs and I think the api is looking a lot better. Thanks, and let me know if you have any thoughts on how overriding render or inherited bindings should be implemented.
This was referenced on 22 Jan 2013
 Closed
For discussion: Extract overridable methods to Backbone.Stickit #55
 Closed
delegateEvents unbinds all already bound events? #57
